"""
Sayanox Guardrail-X Configuration Module

Handles environment variable loading and defines core dataclasses
for configuration, attack payloads, and evaluation results.
"""

import os
from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from enum import Enum


class AttackType(Enum):
    """Enumeration of supported attack types."""
    PROMPT_INJECTION = "prompt_injection"
    GUARDRAIL_BYPASS = "guardrail_bypass"
    SYSTEM_LEAK = "system_leak"
    COGNITIVE_FRAMING = "cognitive_framing"
    MULTI_TURN_STATE = "multi_turn_state"


@dataclass
class Configuration:
    """
    Main configuration container for the Red-Teaming Engine.
    
    Attributes:
        qwen_api_key: API key for Qwen-Coder service.
        qwen_api_endpoint: Base URL for Qwen-Coder API.
        target_api_key: API key for the target LLM service.
        target_api_endpoint: Base URL for the target LLM API.
        max_iterations: Maximum number of mutation iterations to attempt.
        bypass_threshold: Minimum score to consider a bypass successful.
        timeout_seconds: Request timeout in seconds.
        rate_limit_delay: Delay between requests to avoid rate limiting.
        output_path: Directory path for saving reports.
        log_level: Logging level (DEBUG, INFO, WARNING, ERROR).
    """
    qwen_api_key: str
    qwen_api_endpoint: str = "https://api.qwen.ai/v1"
    target_api_key: Optional[str] = None
    target_api_endpoint: str = "https://api.target-llm.com/v1"
    max_iterations: int = 50
    bypass_threshold: float = 0.7
    timeout_seconds: int = 30
    rate_limit_delay: float = 1.0
    output_path: str = "./reports"
    log_level: str = "INFO"
    
    @classmethod
    def from_env(cls) -> "Configuration":
        """Load configuration from environment variables."""
        qwen_api_key = os.getenv("QWEN_API_KEY")
        if not qwen_api_key:
            raise ValueError("QWEN_API_KEY environment variable is required")
        
        return cls(
            qwen_api_key=qwen_api_key,
            qwen_api_endpoint=os.getenv("QWEN_API_ENDPOINT", "https://api.qwen.ai/v1"),
            target_api_key=os.getenv("TARGET_API_KEY"),
            target_api_endpoint=os.getenv("TARGET_API_ENDPOINT", "https://api.target-llm.com/v1"),
            max_iterations=int(os.getenv("MAX_ITERATIONS", "50")),
            bypass_threshold=float(os.getenv("BYPASS_THRESHOLD", "0.7")),
            timeout_seconds=int(os.getenv("TIMEOUT_SECONDS", "30")),
            rate_limit_delay=float(os.getenv("RATE_LIMIT_DELAY", "1.0")),
            output_path=os.getenv("OUTPUT_PATH", "./reports"),
            log_level=os.getenv("LOG_LEVEL", "INFO"),
        )


@dataclass
class AttackPayload:
    """
    Represents a single attack payload generated by the mutator.
    
    Attributes:
        original_intent: The base intent or goal of the attack.
        mutated_prompt: The actual prompt text after mutation.
        attack_type: Type of attack being performed.
        mutation_strategy: Strategy used for mutation (e.g., AST obfuscation).
        metadata: Additional metadata about the payload.
        iteration: Iteration number when this payload was generated.
    """
    original_intent: str
    mutated_prompt: str
    attack_type: AttackType
    mutation_strategy: str
    metadata: Dict[str, Any] = field(default_factory=dict)
    iteration: int = 0
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert payload to dictionary for JSON serialization."""
        return {
            "original_intent": self.original_intent,
            "mutated_prompt": self.mutated_prompt,
            "attack_type": self.attack_type.value,
            "mutation_strategy": self.mutation_strategy,
            "metadata": self.metadata,
            "iteration": self.iteration,
        }


@dataclass
class EvaluationResult:
    """
    Result of evaluating a target LLM response against guardrails.
    
    Attributes:
        payload: The AttackPayload that was evaluated.
        target_response: The raw response from the target LLM.
        bypass_score: Numerical score indicating bypass success (0.0 to 1.0).
        refusal_detected: Whether a refusal pattern was detected.
        semantic_distance: Semantic distance from expected safe response.
        string_similarity: Similarity to known unsafe patterns.
        evaluation_notes: Human-readable notes about the evaluation.
        timestamp: ISO format timestamp of evaluation.
    """
    payload: AttackPayload
    target_response: str
    bypass_score: float
    refusal_detected: bool
    semantic_distance: float
    string_similarity: float
    evaluation_notes: str
    timestamp: str
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert result to dictionary for JSON serialization."""
        return {
            "payload": self.payload.to_dict(),
            "target_response": self.target_response,
            "bypass_score": self.bypass_score,
            "refusal_detected": self.refusal_detected,
            "semantic_distance": self.semantic_distance,
            "string_similarity": self.string_similarity,
            "evaluation_notes": self.evaluation_notes,
            "timestamp": self.timestamp,
        }


def load_env_file(filepath: str = ".env") -> None:
    """
    Load environment variables from a .env file.
    
    Args:
        filepath: Path to the .env file.
    """
    if os.path.exists(filepath):
        with open(filepath, "r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, value = line.split("=", 1)
                    os.environ.setdefault(key.strip(), value.strip())
